--- !ruby/object:Jumpstart::Configuration
application_name: PresentTools
business_name: Humble Daisy, Inc
domain: presenttools.com
support_email: support@presenttools.com
default_from_email: Jumpstart <support@example.com>
business_address: "1342 Arella Boulevard\r\nAnn Arbor, MI 48103"
background_job_processor: sidekiq
email_provider: ''
personal_accounts: true
livereload: true
solargraph: false
register_with_account: false
